#!/usr/bin/env bash
# ─────────────────────────────────────────────
#  Redirect Checker — Docker Hub build & push
#  Usage:
#    ./build-push.sh                  # bumps patch (1.0.0 → 1.0.1)
#    ./build-push.sh minor            # bumps minor (1.0.0 → 1.1.0)
#    ./build-push.sh major            # bumps major (1.0.0 → 2.0.0)
#    ./build-push.sh 2.3.0            # sets an explicit version
# ─────────────────────────────────────────────
set -euo pipefail

# ── Config ─────────────────────────────────
DOCKER_USER="${DOCKER_USER:-}"          # set via env or edit here
APP_NAME="redirect-checker"
VERSION_FILE=".version"

# ── Resolve Docker Hub username ─────────────
if [[ -z "$DOCKER_USER" ]]; then
  DOCKER_USER=$(docker info 2>/dev/null | grep Username | awk '{print $2}' || true)
fi
if [[ -z "$DOCKER_USER" ]]; then
  echo "❌  Cannot detect Docker Hub username."
  echo "    Run:  export DOCKER_USER=your_dockerhub_username"
  exit 1
fi

BACKEND_IMAGE="$DOCKER_USER/${APP_NAME}-backend"
FRONTEND_IMAGE="$DOCKER_USER/${APP_NAME}-frontend"

# ── Version management ───────────────────────
if [[ ! -f "$VERSION_FILE" ]]; then
  echo "1.0.0" > "$VERSION_FILE"
fi
CURRENT=$(cat "$VERSION_FILE")
IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"

BUMP="${1:-patch}"
case "$BUMP" in
  major)         MAJOR=$((MAJOR + 1)); MINOR=0; PATCH=0 ;;
  minor)         MINOR=$((MINOR + 1)); PATCH=0 ;;
  patch)         PATCH=$((PATCH + 1)) ;;
  [0-9]*.[0-9]*.[0-9]*)  # explicit version passed
    IFS='.' read -r MAJOR MINOR PATCH <<< "$BUMP" ;;
  *)
    echo "❌  Unknown argument '$BUMP'. Use: patch | minor | major | X.Y.Z"
    exit 1 ;;
esac

VERSION="${MAJOR}.${MINOR}.${PATCH}"
echo "$VERSION" > "$VERSION_FILE"

echo ""
echo "🚀  Building & pushing  v${VERSION}  →  Docker Hub"
echo "    Backend  : ${BACKEND_IMAGE}"
echo "    Frontend : ${FRONTEND_IMAGE}"
echo ""

# ── Build ────────────────────────────────────
echo "📦  Building backend..."
docker build \
  --platform linux/amd64 \
  -t "${BACKEND_IMAGE}:${VERSION}" \
  -t "${BACKEND_IMAGE}:latest" \
  ./backend

echo "📦  Building frontend..."
docker build \
  --platform linux/amd64 \
  -t "${FRONTEND_IMAGE}:${VERSION}" \
  -t "${FRONTEND_IMAGE}:latest" \
  ./frontend

# ── Push ─────────────────────────────────────
echo ""
echo "⬆️   Pushing backend..."
docker push "${BACKEND_IMAGE}:${VERSION}"
docker push "${BACKEND_IMAGE}:latest"

echo "⬆️   Pushing frontend..."
docker push "${FRONTEND_IMAGE}:${VERSION}"
docker push "${FRONTEND_IMAGE}:latest"

# ── Update docker-compose.prod.yml ───────────
cat > docker-compose.prod.yml <<EOF
# Auto-generated by build-push.sh — do not edit manually
# Version: ${VERSION}
services:
  backend:
    image: ${BACKEND_IMAGE}:${VERSION}
    container_name: redirect-checker-api
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/health')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  frontend:
    image: ${FRONTEND_IMAGE}:${VERSION}
    container_name: redirect-checker-ui
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
EOF

echo ""
echo "✅  Done!"
echo ""
echo "    Version    : ${VERSION}"
echo "    Backend    : ${BACKEND_IMAGE}:${VERSION}"
echo "    Frontend   : ${FRONTEND_IMAGE}:${VERSION}"
echo ""
echo "    To deploy from Hub:"
echo "    docker compose -f docker-compose.prod.yml up -d"
echo ""
